apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-es
  labels:
    component: backup-es
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          # TODO: backup es cluster
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster > /tmp/test.log
          restartPolicy: OnFailure
