kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-home
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/data/jenkins-home"
