kind: PersistentVolume
apiVersion: v1
metadata:
  name: mydata
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/data/mydata"
